# Generated by Django 4.1.1 on 2022-09-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='stroyline',
            new_name='storyline',
        ),
    ]
